In [44]:
import pandas as pd
import numpy as np

In [45]:
def read_data_file(file_path):
    try:
        df = pd.read_csv(file_path)
        return df
    except FileNotFoundError:
        print("file not found")
    except Exception:
        print("could not read the file")

In [46]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [47]:
print(df.columns.tolist())

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [48]:
df.duplicated().count()

np.int64(891)

In [49]:
df.drop_duplicates(inplace=True)

In [50]:
def drop_unnecessary_features(df, cols_to_drop):
    return df.drop(columns=cols_to_drop)

In [55]:
df = drop_unnecessary_features(df, cols_to_drop)

NameError: name 'cols_to_drop' is not defined

In [51]:
def check_data_type(df):
    result = pd.DataFrame({
        "datatype": df.dtypes,
        "unique_values": df.nunique()
    })
    
    return result.T

In [52]:
data_report = check_data_type(df)

data_report

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
datatype,int64,int64,int64,str,str,float64,int64,int64,str,float64,str,str
unique_values,891,2,3,891,2,88,7,7,681,248,147,3

In [54]:
file_path = "titanic.csv"

df = read_data_file(file_path)

if df is not None:
    print("original data:")
    display(df.head())

    print("original shape:", df.shape)

    df = drop_unnecessary_features(df, cols_to_drop)

    print("data after removing unnecessary features:")
    display(df.head())

    print("new shape:", df.shape)

    print("data quality report:")
    display(check_data_type(df))

original data:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

original shape: (891, 12)

NameError: name 'cols_to_drop' is not defined